config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'store_settings/show'
  get 'store_settings/storefront_setting'
  resources :store_settings, only: :update
  post  'webhooks/dispatcher'
  post  'requests/create'
  get   'requests/delete' # to be edited

  get   '/application',     to: 'storefront#application'
  get   '/old_application', to: 'storefront#old_application'
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
# frozen_string_literal: true

# Request model
# combination_id default is 1
# 1 means that this is the base product
class Request < ApplicationRecord
  belongs_to :store_setting, foreign_key: 'store_id', primary_key: 'store_id'
  validates :store_id,
            presence: true,
            length: { maximum: 14 }
  validates :name,
            presence: true,
            length: { maximum: 14 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email,
            presence: true,
            length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: {
              scope: %i[product_id combination_id],
              message: 'Request should be unique',
              case_sensitive: false
            }
  validates :product_id,
            presence: true,
            length: { maximum: 14 }
  validates :combination_id,
            presence: true,
            length: { maximum: 14 }
end

app/models/store_setting.rb
# frozen_string_literal: true

# Store settings model. Stores application settings for stores
class StoreSetting < ApplicationRecord
  has_many :requests, foreign_key: 'store_id', primary_key: 'store_id'
  validates :store_id,
            presence: true,
            uniqueness: true,
            length: { maximum: 14 }
  validates :subject,
            presence: true,
            length: { maximum: 80 }
  validates :content,
            presence: true,
            length: { maximum: 255 }
  validates :token,
            presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application controller
class ApplicationController < ActionController::Base
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST'
  end
end

app/controllers/requests_controller.rb
# frozen_string_literal: true

# Receives request from storefront applicaiton and saves them in database
class RequestsController < ApplicationController
  skip_before_action :verify_authenticity_token
  after_action :cors_set_access_control_headers

  # Creates a request
  def create
    request = Request.new(request_params)
    head :ok if request.save
  end

  private

  # Params of the request
  def request_params
    params.require(:request).permit(
      :store_id,
      :name,
      :email,
      :product_id,
      :combination_id
    )
  end
end

app/controllers/store_settings_controller.rb
# frozen_string_literal: true

# Controls the settings of the application.
class StoreSettingsController < ApplicationController
  protect_from_forgery with: :null_session, only: :update
  after_action :cors_set_access_control_headers

  # This action returns the "Storefront setting for the store specified"
  # @param [Integer] store_id ID of the specified store
  # @example
  #  /store_settings/storefront_setting?store_id=11589526 #=>{ storefront_enabled: 1 }
  def storefront_setting
    store_id = params[:store_id]
    @store_setting = StoreSetting.find_by(store_id: store_id)
    render json: { storefront_enabled: @store_setting.storefront_enabled }
  end

  # The action shows Application Settings page of the specified store
  # Is called from Ecwid iframe page
  # @param [String] payload Payload generated by Ecwid
  # @see
  #   https://developers.ecwid.com/api-documentation/authentication-in-native-apps#enhanced-security-user-auth Ecwid Documentation
  def show
    response.headers['X-FRAME-OPTIONS'] = 'ALLOWALL'
    permitted = permitted_params_for_show
    store_data = PayloadDecrypter.new(permitted[:payload]).call
    store_id = store_data['store_id']
    token = store_data['access_token']
    @store_settings = StoreSetting.find_by(store_id: store_id)
    if @store_settings
      check_and_update_token(token)
    else
      @store_settings = StoreSetting.create(store_id: store_id, token: token)
    end
  end

  # Updates store_settings with the specified parameters
  # is called from the app settings page
  # If notifications enabled is switched from 0 to 1
  # checks all the products and sends notifications for all
  # ones that are in stock
  # @param [Boolean] storefront_enabled
  # @param [Boolean] notifications_enabled
  # @param [String] subject
  # @param [String] content
  def update
    store_setting = StoreSetting.find(params[:id])
    store_id      = store_setting.store_id
    store_setting.update(store_setting_params)
    if store_setting_params[:notifications_enabled] == 'true'
      requested_products = RequestsHandler::RequestedProducts.new(
        store_id
      ).call
      requested_products.each do |product_id|
        process_emails(store_id, product_id)
      end
    end
  end

  private

  # Calls EmailSender service to process emails for the specified
  # store and product
  # @param [Integer] store_id ID of the store
  # @param [Integer] product_id ID of the product
  def process_emails(store_id, product_id)
    NotificationHandler::EmailSender.new(
      store_id,
      product_id
    ).call
  end

  # Updates store access token if necessary. Token is passed in payload
  # @param [String] token
  def check_and_update_token(token)
    @store_settings.update(token: token) unless @store_settings.token == token
  end

  # Param permitted to display store settings (show action)
  def permitted_params_for_show
    params.permit(:payload)
  end

  #  Param permitted to update store settings (update action)
  def store_setting_params
    params.require(:store_setting).permit(
      :storefront_enabled,
      :notifications_enabled,
      :subject,
      :content
    )
  end
end

app/controllers/storefront_controller.rb
# frozen_string_literal: true

# Returns the JavaScript code for the application on the storefront
class StorefrontController < ApplicationController
  skip_before_action :verify_authenticity_token

  # Returns JS code for new Ecwid storefront
  def application
    respond_to(:js)
  end

  # Returns JS code for old Ecwid storefront
  def old_application
    respond_to(:js)
  end
end

app/controllers/webhooks_controller.rb
# frozen_string_literal: true

# Dispatches webhooks and calls the corresponding services
class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  after_action :cors_set_access_control_headers

  # Calls corresponding service depending on what event is returned by the webhook
  # 1) If a product is updated, checks whether there are any requests for the product
  #    and sends notifications for requests, which entity is in stock
  # 2) If a product is deleted, removes all the
  # @note
  #   in this context entityId of Ecwid's webhook is product ID
  #   in case of "application.installed" webhook it doesn't refer to product
  #   but we don't use it in this case
  # @see
  #   https://developers.ecwid.com/api-documentation/webhooks Ecwid documentation
  def dispatcher
    head :ok
    webhook     = webhook_params
    store_id    = webhook[:storeId]
    product_id  = webhook[:entityId]
    if webhook[:eventType] == 'product.updated'
      if product_requested?(store_id, product_id)
        NotificationHandler::EmailSender.new(store_id, product_id).call
      end
    elsif webhook[:eventType] == 'product.deleted'
      RequestsHandler::DeleteByStoreAndProduct.new(
        webhook[:storeId],
        webhook[:entityId]
      ).call
    end
  end

  private

  # params permitted for the webhook
  def webhook_params
    params.permit(
      :storeId,
      :entityId,
      :eventType
    )
  end

  # Checks, whether there are any requests for the product
  def product_requested?(store_id, product_id)
    Request.exists?(store_id: store_id, product_id: product_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OosRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="height=device-height, width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/store_settings/_contents_form.html.erb
<div class="a-card a-card--normal">
    <div class="a-card__paddings">
        <%= form_for @store_settings, remote: true do |f| %>
        <div class="form-area">
            <div class="form-area__title">Email Subject</div>
            <div class="form-area__content">
                <div class="fieldsets-batch">
                    <div class="fieldset" id="subjfield">
                        <div class="field field--medium">
                            <label class="field__label">Subject</label>
                            <%= f.text_field :subject, class: "field__input", value: f.object.subject, maxlength: 80, tabindex: 4, required: "required" %>
                            <div class="field__placeholder">Subject</div>
                        </div>
                        <div class="field__error">Cannot be empty</div>
                    </div>
                </div>
            </div>

            <div class="form-area__title">Email Text</div>
            <div class="form-area__content">
                <div class="fieldset fieldset--textarea" id="contentfield">
                    <div class="field">
                        <%= f.text_area :content, class: "field__textarea", tabindex: 1, maxlength: 250, required: "required" %>
                        <div class="field__placeholder">Text</div>
                    </div>
                    <div class="field__error">Cannot be empty</div>
                    <div class="fieldset__note">Use {customerName} to call your customer's name.</div>
                </div>
            </div>

            <div class="form-area__action">
                <%= f.submit "Save", class: "btn btn-primary btn-medium btn-save" %>
                <button class="btn btn-link" id="btn-revert" style="float:right">Revert to default</button>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/store_settings/_head_content.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="https://djqizrxa6f10j.cloudfront.net/ecwid-sdk/css/1.3.2/ecwid-app-ui.css" />

  <!-- Include Ecwid JS SDK -->
  <script src="https://djqizrxa6f10j.cloudfront.net/ecwid-sdk/js/1.2.5/ecwid-app.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script>
      // Initialize the application
      EcwidApp.init({
          app_id: "back-in-stock-flint", // your client_id
          autoloadedflag: true,
          autoheight: true
      });

      var storeId = <%= @store_settings.store_id %>;
      var controller_url = "<%= store_setting_path(@store_settings) %>"
  </script>

  <%= javascript_include_tag "cp_scripts" %>
<% end %>

app/views/store_settings/_notifications_form.html.erb
<div class="a-card a-card--compact">
    <div class="a-card__paddings">
        <div class="iconable-block iconable-block--hide-in-mobile">
            <div class="iconable-block__infographics">
                <span class="iconable-block__icon">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="511.626px" height="511.627px" viewBox="0 0 511.626 511.627" style="enable-background:new 0 0 511.626 511.627;" xml:space="preserve">
                    <g>
                        <path d="M498.208,68.235c-8.945-8.947-19.701-13.418-32.261-13.418H45.682c-12.562,0-23.318,4.471-32.264,13.418   C4.471,77.18,0,87.935,0,100.499v310.633c0,12.566,4.471,23.312,13.418,32.257c8.945,8.953,19.701,13.422,32.264,13.422h420.266   c12.56,0,23.315-4.469,32.261-13.422c8.949-8.945,13.418-19.697,13.418-32.257V100.499   C511.626,87.935,507.158,77.18,498.208,68.235z M475.078,411.125c0,2.475-0.903,4.616-2.714,6.424   c-1.81,1.81-3.949,2.706-6.42,2.706H45.679c-2.474,0-4.616-0.896-6.423-2.706c-1.809-1.808-2.712-3.949-2.712-6.424V191.858   c6.09,6.852,12.657,13.134,19.7,18.843c51.012,39.209,91.553,71.374,121.627,96.5c9.707,8.186,17.607,14.561,23.697,19.13   c6.09,4.571,14.322,9.185,24.694,13.846c10.373,4.668,20.129,6.991,29.265,6.991h0.287h0.284c9.134,0,18.894-2.323,29.263-6.991   c10.376-4.661,18.613-9.274,24.701-13.846c6.089-4.569,13.99-10.944,23.698-19.13c30.074-25.126,70.61-57.291,121.624-96.5   c7.043-5.708,13.613-11.991,19.694-18.843V411.125L475.078,411.125z M475.078,107.92v3.14c0,11.229-4.421,23.745-13.271,37.543   c-8.851,13.798-18.419,24.792-28.691,32.974c-36.74,28.936-74.897,59.101-114.495,90.506c-1.14,0.951-4.474,3.757-9.996,8.418   c-5.514,4.668-9.894,8.241-13.131,10.712c-3.241,2.478-7.471,5.475-12.703,8.993c-5.236,3.518-10.041,6.14-14.418,7.851   c-4.377,1.707-8.47,2.562-12.275,2.562h-0.284h-0.287c-3.806,0-7.895-0.855-12.275-2.562c-4.377-1.711-9.185-4.333-14.417-7.851   c-5.231-3.519-9.467-6.516-12.703-8.993c-3.234-2.471-7.614-6.044-13.132-10.712c-5.52-4.661-8.854-7.467-9.995-8.418   c-39.589-31.406-77.75-61.57-114.487-90.506c-27.981-22.076-41.969-49.106-41.969-81.083c0-2.472,0.903-4.615,2.712-6.421   c1.809-1.809,3.949-2.714,6.423-2.714h420.266c1.52,0.855,2.854,1.093,3.997,0.715c1.143-0.385,1.998,0.331,2.566,2.138   c0.571,1.809,1.095,2.664,1.57,2.57c0.477-0.096,0.764,1.093,0.859,3.571c0.089,2.473,0.137,3.718,0.137,3.718V107.92   L475.078,107.92z" style="fill: #189dee;"></path></g>
                    </svg>
                </span>
            </div>
            <div class="iconable-block__content">
                <div class="status-block">
                    <div class="status-block__central">
                        <div class="status-block__header">
                            <span class="status-block__title">Notifications</span>
                        </div>
                        <div class="status-block__content">
                            <p>Send back in stock notifications</p>
                        </div>
                    </div>
                    
                    <div class="status-block__primary-action">
                        <label class="checkbox big">
                            <input name="" type="checkbox" id="notificationscheck" <%= 'checked' if @store_settings.notifications_enabled %> >
                            <div data-on="enabled" data-off="disabled">
                                <div></div>
                            </div>
                            <span class="checkbox__on-text-placeholder">enabled</span>
                            <span class="checkbox__off-text-placeholder">disabled</span>
                        </label>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/store_settings/_storefront_form.html.erb
<div class="a-card a-card--compact">
    <div class="a-card__paddings">
        <div class="iconable-block iconable-block--hide-in-mobile">
            <div class="iconable-block__infographics">
                <span class="iconable-block__icon">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 502.56 502.56" style="enable-background:new 0 0 502.56 502.56;" xml:space="preserve">
                    <g>
                        <g>
                            <g>
                                <path d="M467.28,467.496h24v-128h-24V129.328l12.088,3.888l23.192-46.392L251.28,3.064L0,86.824l23.192,46.392l12.088-3.888     v354.168h-32v16h32h432h32v-16h-32V467.496z M475.28,355.496v96h-8v-96H475.28z M215.6,483.496H107.28v-216h80v184h-64v16h80v-16     v-184v-16v-16h16v180.32c-9.792,8.792-16,21.504-16,35.68C203.28,463.8,207.968,474.992,215.6,483.496z M251.28,483.496     c-17.648,0-32-14.352-32-32s14.352-32,32-32s32,14.352,32,32S268.928,483.496,251.28,483.496z M296.936,309.84l-11.312,11.312     l10.344,10.344l-31.04,31.04l32.464-119.04h92.256l29.6,82.896l-97.728,45.104h-42.928l28.688-28.688l10.344,10.344     l11.312-11.312L296.936,309.84z M236.528,405.84c-0.424,0.136-0.832,0.304-1.248,0.456v-138.8h38.984L236.528,405.84z      M286.96,483.496c4.144-4.624,7.4-10.032,9.52-16h77.6c2.12,5.968,5.376,11.376,9.52,16H286.96z M419.28,483.496     c-17.648,0-32-14.352-32-32s14.352-32,32-32s32,14.352,32,32S436.928,483.496,419.28,483.496z M451.28,415.816     c-8.504-7.632-19.696-12.32-32-12.32c-26.472,0-48,21.528-48,48h-72c0-25.648-20.232-46.592-45.56-47.88l4.4-16.12h66.92     l99.608-45.976l4.992,13.976h21.64V415.816z M451.28,339.496h-10.36l-34.288-96h12.648v-16h-152v16h13.528l-2.184,8H235.28v-16     h16v-16h-80v16h16v16h-96v232h-40v-288h400V339.496z M451.28,179.496h-400v-55.312l200-64.28l200,64.288V179.496z M251.28,43.088     L31.368,113.776L22.56,96.168l228.72-76.24L480,96.168l-8.808,17.608L251.28,43.088z" style="fill: #189dee;"></path>
                                <rect x="243.28" y="91.496" width="16" height="16" style="fill: #189dee;"></rect>
                                <rect x="275.28" y="91.496" width="16" height="16" style="fill: #189dee;"></rect>
                                <rect x="211.28" y="91.496" width="16" height="16" style="fill: #189dee;"></rect>
                            </g>
                        </g>
                    </g>
                    </svg>
                </span>
            </div>
            <div class="iconable-block__content">
                <div class="status-block">
                    <div class="status-block__central">
                        <div class="status-block__header">
                            <span class="status-block__title">Storefront</span>
                        </div>
                        <div class="status-block__content">
                            <p>Allow customers to request notifications</p>
                        </div>
                    </div>
                    
                    <div class="status-block__primary-action">
                        <label class="checkbox big">
                            <input name="" type="checkbox" id="storefrontcheck" <%= 'checked' if @store_settings.storefront_enabled %> > 
                            <div data-on="enabled" data-off="disabled">
                                <div></div>
                            </div>
                            <span class="checkbox__on-text-placeholder">enabled</span>
                            <span class="checkbox__off-text-placeholder">disabled</span>
                        </label>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/store_settings/show.html.erb
<%= render 'head_content' %>
<div class="settings-page">
    <div class="settings-page__header">
        <div class="settings-page__titles settings-page__titles--left">
            <h1 class="settings-page__title">Back in stock notifications</h1>
            <div class="settings-page__subtitle">Allow your customers to request an email notification, that will be sent, when an out-of-stock product is in stock again.</div>
        </div>
    </div>

    <div class="settings-page__body">

        <div class="named-area">

            <div class="named-area__header" style="">
                <div class="named-area__titles">
                    <h4 class="named-area__title h4">General Settings</h4>
                    <span class="named-area__subtitle"></span>
                </div>
            </div>

            <div class="named-area__body">
                <%= render 'storefront_form' %>
                <%= render 'notifications_form' %>
            </div>

        </div>

        <div class="named-area">

            <div class="named-area__header" style="">
                <div class="named-area__titles">
                    <h4 class="named-area__title h4">Email Contents</h4>
                    <span class="named-area__subtitle">Edit the content of the notifications, that your customers receive</span>
                </div>
            </div>

            <br>

            <div class="named-area__body">
                <%= render 'contents_form' %>
            </div>
        </div>
    </div>
</div>
    <script src="https://djqizrxa6f10j.cloudfront.net/ecwid-sdk/css/1.3.0/ecwid-app-ui.min.js"></script>

</body>

app/views/store_settings/update.html.erb
<h1>StoreSettings#update</h1>
<p>Find me in app/views/store_settings/update.html.erb</p>